from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_JUSTIFY
import io

def generate_rti_pdf(
    rti_application: str,
    department: str,
    applicant_name: str,
    applicant_address: str,
    applicant_phone: str
):
    buffer = io.BytesIO()
    
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=inch,
        leftMargin=inch,
        topMargin=inch,
        bottomMargin=inch
    )

    styles = getSampleStyleSheet()
    story = []

    # Title Style
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=16,
        textColor=colors.HexColor('#1a3c5e'),
        alignment=TA_CENTER,
        spaceAfter=6,
        fontName='Helvetica-Bold'
    )

    # Subtitle Style
    subtitle_style = ParagraphStyle(
        'Subtitle',
        parent=styles['Normal'],
        fontSize=10,
        textColor=colors.HexColor('#f97316'),
        alignment=TA_CENTER,
        spaceAfter=4,
    )

    # Header Note Style
    header_note_style = ParagraphStyle(
        'HeaderNote',
        parent=styles['Normal'],
        fontSize=8,
        textColor=colors.gray,
        alignment=TA_CENTER,
        spaceAfter=12,
    )

    # Body Style
    body_style = ParagraphStyle(
        'CustomBody',
        parent=styles['Normal'],
        fontSize=11,
        leading=18,
        textColor=colors.HexColor('#1e293b'),
        alignment=TA_JUSTIFY,
        spaceAfter=8,
        fontName='Helvetica'
    )

    # Label Style
    label_style = ParagraphStyle(
        'Label',
        parent=styles['Normal'],
        fontSize=9,
        textColor=colors.gray,
        alignment=TA_LEFT,
        spaceAfter=2,
    )

    # Add Header
    story.append(Paragraph("RTI SAATHI", title_style))
    story.append(Paragraph("AI-Powered RTI Application Generator", subtitle_style))
    story.append(Paragraph("Generated under Right to Information Act, 2005", header_note_style))
    story.append(HRFlowable(width="100%", thickness=2, color=colors.HexColor('#1a3c5e')))
    story.append(Spacer(1, 0.2 * inch))

    # Department Badge
    dept_style = ParagraphStyle(
        'Dept',
        parent=styles['Normal'],
        fontSize=10,
        textColor=colors.HexColor('#1a3c5e'),
        alignment=TA_LEFT,
        spaceAfter=4,
        fontName='Helvetica-Bold'
    )
    story.append(Paragraph(f"To Department: {department}", dept_style))
    story.append(Paragraph(f"Applicant: {applicant_name}", label_style))
    if applicant_phone:
        story.append(Paragraph(f"Phone: {applicant_phone}", label_style))
    story.append(Spacer(1, 0.1 * inch))
    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.lightgrey))
    story.append(Spacer(1, 0.2 * inch))

    # RTI Application Content
    lines = rti_application.split('\n')
    for line in lines:
        line = line.strip()
        if not line:
            story.append(Spacer(1, 0.1 * inch))
        elif line.isupper() and len(line) > 3:
            # Section headers
            section_style = ParagraphStyle(
                'Section',
                parent=styles['Normal'],
                fontSize=11,
                textColor=colors.HexColor('#1a3c5e'),
                fontName='Helvetica-Bold',
                spaceAfter=4,
                spaceBefore=8
            )
            story.append(Paragraph(line, section_style))
        else:
            story.append(Paragraph(line, body_style))

    # Footer
    story.append(Spacer(1, 0.3 * inch))
    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.lightgrey))
    story.append(Spacer(1, 0.1 * inch))

    footer_style = ParagraphStyle(
        'Footer',
        parent=styles['Normal'],
        fontSize=8,
        textColor=colors.gray,
        alignment=TA_CENTER,
    )
    story.append(Paragraph(
        "This RTI application was generated by RTI Saathi — An AI tool for Indian citizens. "
        "Please verify all details before submission. RTI Saathi is not a legal service.",
        footer_style
    ))
    story.append(Paragraph(
        "File online at: rtionline.gov.in | Built for EduNet x IBM Skillsphere Internship",
        footer_style
    ))

    doc.build(story)
    buffer.seek(0)
    return buffer